---
# task file for joe-speedboat.nextcloud
- include: 'prerequisites.yml'

- name: ensure {{ nextcloud_webroot }} is present
  file:
    name: '{{ nextcloud_webroot }}'
    state: directory
  register: new_installation

- include: 'installation.yml'
  when: new_installation.changed

- name: ensure .user.ini config is present
  template:
    src: user.ini.j2
    dest: '{{ nextcloud_webroot }}/.user.ini'
  notify:
    - reload nginx
    - reload php-fpm

- include: 'permissions.yml'
...
